standard,=,module,"standard"
print,=,attr,standard,print
error,=,attr,standard,error

cursor,=,namespace,
    goto,=,function,x,y,
        x_s_f,=,attr,x,to_string,
        x_s,=,call,x_s_f,
        y_s_f,=,attr,y,to_string,
        y_s,=,call,y_s_f,
        s,=,"\e[",
        s,+=,x_s,
        s,+=,";",
        s,+=,y_s,
        s,+=,"H ",
        call,print,s,
    end,
    up,=,function,s,
        s_s_f,=,attr,s,to_string,
        s_s,=,call,s_s_f,
        s,=,"\e[",
        s,+=,s_s,
        s,+=,"A",
        call,print,s,
    end,
    down,=,function,s,
        s_s_f,=,attr,s,to_string,
        s_s,=,call,s_s_f,
        s,=,"\e[",
        s,+=,s_s,
        s,+=,"B",
        call,print,s,
    end,
    right,=,function,s,
        s_s_f,=,attr,s,to_string,
        s_s,=,call,s_s_f,
        s,=,"\e[",
        s,+=,s_s,
        s,+=,"C",
        call,print,s,
    end,
    left,=,function,s,
        s_s_f,=,attr,s,to_string,
        s_s,=,call,s_s_f,
        s,=,"\e[",
        s,+=,s_s,
        s,+=,"D",
        call,print,s,
    end,
    clear,=,function,
        call,print,"\e[2J"
    end,
    color,=,function,c_name,
        switch,
            case,c_name == "black",
                n,=,30,
                export,n,
            end,
            case,c_name == "red",
                n,=,31,
                export,n,
            end,
            case,c_name == "green",
                n,=,32,
                export,n,
            end,
            case,c_name == "yellow",
                n,=,33,
                export,n,
            end,
            case,c_name == "blue",
                n,=,34,
                export,n,
            end,
            case,c_name == "magenta",
                n,=,35,
                export,n,
            end,
            case,c_name == "cyan",
                n,=,36,
                export,n,
            end,
            case,c_name == "white",
                n,=,37,
                export,n,
            end,
            case,true,
                call,error,
            end,
            export,n,
        end,
        s,=,"\e[",
        n_s_f,=,attr,n,to_string,
        n_s,=,call,n_s_f,
        s,+=,n_s,
        s,+=,"m",
        call,print,s,
    end,
end,