print,=,function,s,
   c_s,=,"write $STDOUT \"",
   c_s,+=,s,
   c_s,+=,"\"",
   rustcall,c_s,
end,

file,=,namespace,
    new,=,function,fname,
        self,=,empty,
        return,self,
    read,=,function,self,
        return,"",
    end,
    write,=,function,self,content,
    end,
end,

error,=,function,message,
    rustcall,"error"
end,