print,=,function,args,file,
end,

file,=,namespace,
    new,=,function,fname,
       ,self,=,empty,
       ,return,self,
    read,=,function,self,
       ,return,"",
    end,
    write,=,function,self,content,
    end,
end,